### ISSUE TITLE
Delete this Filth

### ISSUE THREAD

**Issue by shahanstudios** [MergeMyPullRequest/order-splitter#24]

**Comment by dumbbillyhardy** [comment]
I think this issue mistakenly filed. 

If it was not, please feel free to provide more details on what needs to be improved and how.

Webclient: https://mergemypullrequest.github.io/order-splitter/
Chrome Extension: https://chrome.google.com/webstore/detail/order-splitter/jhdgghdjlhghholhhlmfgilboekekbjm?utm_source=chrome-ntp-icon

**Comment by shahanstudios** [comment]
You're correct, I believe I had forgotten to log out of my Github at my workplace and had my identity taken advantage of.

**Comment by dumbbillyhardy** [comment]
I'll go ahead and close this issue then.
