### ISSUE TITLE
Show tip % and tax %

### ISSUE THREAD

**Issue by Fostecks** [MergeMyPullRequest/order-splitter#42]

**Comment by jonsmithers** [comment]
I think these are shown in tooltips.

![screen shot 2017-07-12 at 12 49 46 pm](https://user-images.githubusercontent.com/2660313/28129257-a842112c-6700-11e7-870b-ef18fd5812bf.png)

Is there a better way to present this information?

**Comment by Fostecks** [comment]
This doesn't seem to work for the tax or tip on the totals row (using reference https://jonsmithers.github.io/order-splitter/?tax=2.91&fee=4.78&tip=8.91&Larry=14.55&Benjamin=11.49&Smithers=8.5&Daniel=9.99)

**Comment by jonsmithers** [comment]
ah....that's a valid point
