### ISSUE TITLE
Fair order splitter is not fair

### ISSUE THREAD

**Issue by yrral86** [MergeMyPullRequest/order-splitter#47]
Why are fees split evenly instead of prorated?  If I buy a $2 side item, I shouldn't have to pay $4 for it.  Instead, I will just not order it and everyone else will pay more.

**Comment by jonsmithers** [comment]
Hm. I agree. It definitely seems like they should be prorated.

**Comment by jonsmithers** [comment]
This is currently deployed to [jonsmithers.github.io/order-splitter](https://jonsmithers.github.io/order-splitter/) and can be compared directly with [mergemypullrequest.github.io/order-splitter](https://mergemypullrequest.github.io/order-splitter/).
